source 'http://10.0.93.53:88/icp_mobile/icp_mobile_ios/icp_mobile_specs.git'
source 'https://github.com/icpmobile/ICPMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'


target 'HTNetworkKit_Example' do
  pod 'HTNetworkKit', :path => '../' 
  
  target 'HTNetworkKit_Tests' do
    inherit! :search_paths

    
  end
end
